#!/usr/bin/env python3
"""Validate portable SVGs, explicit rendition metadata, provenance, and reproducibility."""
import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path
import xml.etree.ElementTree as ET

ROOT=Path(__file__).resolve().parents[1]
NS='{http://www.w3.org/2000/svg}'
ALLOWED={'svg','title','desc','g','path','rect','circle','ellipse','line','polygon'}
ERRORS=[]


def require(condition,message):
    if not condition: ERRORS.append(message)


def snapshot():
    paths=[ROOT/name for name in ('manifest.json','catalog/data.js','docs/catalog.md','docs/inventory.md','docs/overview.svg','docs/compact-comparison.svg','docs/web-overview.svg')]
    for folder in ('icons','variants','examples','docs/contact-sheets'):
        paths.extend((ROOT/folder).rglob('*.svg'))
    return {str(p.relative_to(ROOT)):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths}


def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--rebuild',action='store_true',help='Verify rebuilding changes no generated bytes.')
    args=parser.parse_args()
    manifest=json.loads((ROOT/'manifest.json').read_text())
    icons=manifest['icons']; palette=set(manifest['palette'].values())
    require(manifest['schemaVersion']==2,'Expected rendition-aware schema 2')
    require(manifest['count']==len(icons),'Manifest count differs from concept count')
    require(len({i['id'] for i in icons})==len(icons),'Duplicate icon identifiers')
    files={}; bodies={}
    marks={m['id']:m for m in json.loads((ROOT/'src/brands/marks.json').read_text())['icons']}
    for icon in icons:
        require(icon['category'] in manifest['categories'],f"Unknown category: {icon['id']}")
        require(bool(icon['description']) and bool(icon['tags']),f"Missing metadata: {icon['id']}")
        require(re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*',icon['id']),f"Invalid slug: {icon['id']}")
        require(icon['file']==f"icons/{icon['category']}/{icon['id']}.svg",f"Invalid canonical path: {icon['id']}")
        require(icon['renditions'][icon['style']]['file']==icon['file'],f"Missing canonical rendition: {icon['id']}")
        if icon['category'] in ('socials','interface','channels'):
            require(icon['style']=='illustrated' and icon['size']==256,f"Expected cel-shaded default: {icon['id']}")
            require(icon['recommendedMinSize']==64,f"Incorrect recommended cel size: {icon['id']}")
        for style,rendition in icon['renditions'].items():
            size=rendition['size']
            require(size==(256 if style=='illustrated' else 24),f"Incorrect grid: {icon['id']}/{style}")
            require(rendition['viewBox']==[0,0,size,size],f"Incorrect metadata viewBox: {icon['id']}/{style}")
            require(rendition['file'] in rendition['tones'].values(),f"Canonical tone missing: {icon['id']}/{style}")
            if style in ('compact','brand'):
                require(set(rendition['tones'])=={'ink','ivory'},f"Missing tone: {icon['id']}/{style}")
            for filename in set(rendition['tones'].values()):
                require(filename not in files,f'Duplicate asset ownership: {filename}')
                files[filename]=size
                file=ROOT/filename
                require(file.is_file(),f'Missing asset: {filename}')
                if not file.is_file(): continue
                try: tree=ET.fromstring(file.read_text())
                except ET.ParseError as e: ERRORS.append(f'{filename}: {e}'); continue
                require(tree.tag==NS+'svg',f'{filename}: missing SVG namespace')
                require(tree.get('viewBox')==f'0 0 {size} {size}',f'{filename}: incorrect viewBox')
                require(tree.get('width')==str(size) and tree.get('height')==str(size),f'{filename}: incorrect dimensions')
                require(tree.find(NS+'title') is not None and tree.find(NS+'desc') is not None,f'{filename}: missing accessibility metadata')
                for element in tree.iter():
                    tag=element.tag.removeprefix(NS)
                    require(tag in ALLOWED,f'{filename}: unsupported element {tag}')
                    for key,value in element.attrib.items():
                        require(not key.startswith('on') and key not in ('style','class','href'),f'{filename}: dynamic behavior {key}')
                        require('url(' not in value and 'currentColor' not in value,f'{filename}: indirect style value')
                        if key in ('fill','stroke'):
                            require(value=='none' or value in palette,f'{filename}: non-palette color {value}')
                    if tag=='path':
                        require(bool(re.fullmatch(r'[MmLlHhVvCcSsQqTtAaZz0-9eE.,+\s-]+',element.get('d',''))),f'{filename}: invalid path characters')
                    for key in ('width','height','r','rx','ry'):
                        if key in element.attrib: require(float(element.get(key))>=0,f'{filename}: negative {key}')
                    if tag=='rect':
                        require(not (element.get('x')=='0' and element.get('y')=='0' and element.get('width')==str(size) and element.get('height')==str(size)),f'{filename}: background rectangle')
                if icon['category'] in ('socials','interface','channels') and style=='illustrated':
                    fills={e.get('fill') for e in tree.iter() if e.get('fill') not in (None,'none',manifest['palette']['ink'])}
                    require(len(fills)>=3,f'{filename}: missing distinct cel-shaded material planes')
                if filename==icon['file']:
                    body=ET.tostring(tree.find(NS+'g'))
                    require(body not in bodies,f"Identical drawings: {icon['id']} and {bodies.get(body)}")
                    bodies[body]=icon['id']
                if icon['category']=='socials':
                    mark=marks[icon['id']]
                    paths=[p for p in tree.findall('.//'+NS+'path') if p.get('data-brand-face')=='true']
                    require(len(paths)==1 and paths[0].get('d')==mark['path'],f'{filename}: source brand geometry changed')
                    require(hashlib.sha256(mark['path'].encode()).hexdigest()==icon['sourcePathSha256'],f'{filename}: source hash mismatch')
                    require(icon['attribution'] in tree.find(NS+'desc').text,f'{filename}: missing attribution')
    actual={str(p.relative_to(ROOT)) for folder in ('icons','variants') for p in (ROOT/folder).rglob('*.svg')}
    require(set(files)==actual,f'Orphaned or missing assets: {set(files).symmetric_difference(actual)}')
    require(manifest['assetCount']==len(files),'Incorrect asset count')
    for style,count in manifest['styles'].items():
        require(count==sum(style in icon['renditions'] for icon in icons),f'Incorrect {style} count')
    data=(ROOT/'catalog/data.js').read_text().split('window.ICON_LIBRARY = ',1)[1].rstrip(';\n')
    browser=json.loads(data)
    require({k:v for k,v in browser.items() if k!='assets'}==manifest,'Browser metadata differs from manifest')
    require(set(browser['assets'])==set(files),'Browser assets differ from exported assets')
    for filename,content in browser['assets'].items():
        require(content==(ROOT/filename).read_text(),f'Stale browser asset: {filename}')
    for folder in ('examples','docs/contact-sheets'):
        for file in (ROOT/folder).glob('*.svg'):
            try: ET.fromstring(file.read_text())
            except ET.ParseError as e: ERRORS.append(f'{file}: {e}')
    for file in ('index.html','catalog/style.css','catalog/app.js','docs/usage.md','docs/design-system.md','catalog/fonts/Roboto-OFL.txt','catalog/fonts/Sora-OFL.txt','src/brands/LICENSE.txt','THIRD_PARTY_NOTICES.md'):
        require((ROOT/file).is_file(),f'Missing supporting file: {file}')
    if args.rebuild:
        before=snapshot()
        subprocess.run([sys.executable,str(ROOT/'scripts/build.py')],check=True,cwd=ROOT)
        require(before==snapshot(),'Generated output is not reproducible; rebuild and review changed artifacts.')
    if ERRORS:
        print('\n'.join(ERRORS),file=sys.stderr); return 1
    print(f'Validated {len(icons)} concepts / {len(files)} portable SVGs, renditions, provenance, and catalog'+(' — reproducible build confirmed.' if args.rebuild else '.'))
    return 0


if __name__=='__main__': raise SystemExit(main())
